### ISSUE TITLE
No audio on .cia version

### ISSUE THREAD

**Issue by eats7** [masterfeizz/EDuke3D#1]
I can get audio on the homebrew menu version but the cia version has no audio whatsoever using the newest beta

new3dsXL a9lh luma3ds 11.0

**Comment by masterfeizz** [comment]
You need to have a dumped DSP firmware on your /3ds folder. You can use [DSP Dump](https://github.com/Cruel/DspDump) to do so.

**Comment by eats7** [comment]
Aye, totally missed this. Im sorry, thank you !
